# Generated by Django 4.2 on 2023-11-04 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(db_column='category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Todo_List_App.category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completedDate',
            field=models.DateTimeField(blank=True, db_column='completeddate', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='createdDate',
            field=models.DateTimeField(db_column='createddate', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateTimeField(db_column='duedate'),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskTitle',
            field=models.CharField(db_column='tasktitle', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(db_column='_user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='activity',
            table='_activitydetails',
        ),
        migrations.AlterModelTable(
            name='category',
            table='_categorydetails',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='_userdetails',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='_profiledetails',
        ),
        migrations.AlterModelTable(
            name='task',
            table='_taskdetails',
        ),
    ]
