# Generated by Django 5.0.2 on 2024-04-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0002_task_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
