# Generated by Django 4.2 on 2023-06-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0003_alter_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.AlterField(
            model_name='task',
            name='taskTitle',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
