# Generated by Django 4.2 on 2023-06-08 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0014_remove_task_taskdesc_alter_task_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 9, 18, 43, 6, 370156, tzinfo=datetime.timezone.utc)),
        ),
    ]
