# Generated by Django 4.2 on 2023-06-10 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0017_alter_task_duedate_completedtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtask',
            name='completionDate',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time',
        ),
        migrations.AddField(
            model_name='task',
            name='completedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='completedtask',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Todo_List_App.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskTitle',
            field=models.CharField(max_length=100),
        ),
    ]
