# Generated by Django 4.2 on 2023-06-10 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0018_remove_completedtask_completiondate_remove_task_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 10, 7, 31, 47, 926405, tzinfo=datetime.timezone.utc)),
        ),
    ]
