# Generated by Django 4.2 on 2023-06-11 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0022_alter_task_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 19, 45, 15, 479292, tzinfo=datetime.timezone.utc)),
        ),
    ]
