# Generated by Django 4.2 on 2023-06-12 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0028_alter_task_category_alter_task_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 17, 16, 49, 442920, tzinfo=datetime.timezone.utc)),
        ),
    ]
