# Generated by Django 4.2 on 2023-06-13 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0031_alter_task_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 13, 6, 10, 43, 883182, tzinfo=datetime.timezone.utc)),
        ),
    ]
