# Generated by Django 4.2 on 2023-06-14 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0039_alter_task_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 14, 15, 42, 38, 13472, tzinfo=datetime.timezone.utc)),
        ),
    ]
