# Generated by Django 4.2 on 2023-06-15 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0041_alter_task_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 15, 5, 44, 4, 351170, tzinfo=datetime.timezone.utc)),
        ),
    ]
