# Generated by Django 4.2 on 2023-06-15 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0044_task_user_alter_task_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 15, 10, 30, 57, 223277, tzinfo=datetime.timezone.utc)),
        ),
    ]
