# Generated by Django 4.2 on 2023-06-15 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0045_alter_task_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed_tasks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 15, 10, 36, 3, 225168, tzinfo=datetime.timezone.utc)),
        ),
    ]
