# Generated by Django 4.2 on 2023-06-15 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0050_alter_task_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 15, 16, 31, 21, 655838, tzinfo=datetime.timezone.utc)),
        ),
    ]
