# Generated by Django 4.2 on 2023-06-18 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0052_category_user_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='"H:\Todo_List\Todo_List\\media\\profile_pictures\\default.jpg"', upload_to='profile_pictures'),
        ),
        migrations.AlterField(
            model_name='task',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 18, 14, 55, 37, 708047, tzinfo=datetime.timezone.utc)),
        ),
    ]
