# Generated by Django 4.2 on 2023-09-06 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0056_alter_task_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 14, 15, 2, 189003, tzinfo=datetime.timezone.utc)),
        ),
    ]
