# Generated by Django 4.2 on 2023-09-06 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0057_alter_task_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='media/default.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='task',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 14, 39, 34, 167816, tzinfo=datetime.timezone.utc)),
        ),
    ]
