# Generated by Django 4.2 on 2023-09-06 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0059_alter_profile_profile_picture_alter_task_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 18, 6, 36, 501019, tzinfo=datetime.timezone.utc)),
        ),
    ]
