# Generated by Django 4.2 on 2023-09-11 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0067_solve_alter_task_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 11, 17, 45, 6, 188452, tzinfo=datetime.timezone.utc)),
        ),
    ]
