# Generated by Django 4.2 on 2023-09-12 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0069_alter_task_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 8, 39, 40, 518517, tzinfo=datetime.timezone.utc)),
        ),
    ]
