# Generated by Django 4.2 on 2023-09-13 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0070_alter_task_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 13, 17, 55, 32, 843979, tzinfo=datetime.timezone.utc)),
        ),
    ]
