# Generated by Django 4.2 on 2023-09-17 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0075_task_important_alter_task_createddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='important',
        ),
        migrations.AlterField(
            model_name='task',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 17, 8, 39, 7, 480125, tzinfo=datetime.timezone.utc)),
        ),
    ]
