# Generated by Django 4.2 on 2023-09-17 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0076_remove_task_important_alter_task_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 17, 13, 52, 49, 240041, tzinfo=datetime.timezone.utc)),
        ),
    ]
